Repository wp-cli/search-replace-command, pull requests merged in 2023-02, with the labels that each got.

#177 Make is_text_col's search case-insensitive for sqlite support
  src/Search_Replace_Command.php
Labels: command:search-replace

#178 Replace empty namespace autoloader with classmap
  composer.json
Labels: scope:distribution

#179 Add `composer phpcbf` and allow `wordpress-core-installer`
  composer.json
Labels: scope:testing
